name: Dinit on debian-bullseye-amd64 CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  Debian-bullseye-amd64_build:

    runs-on: ubuntu-latest
    container:
      image: debian:bullseye

    steps:
    - uses: actions/checkout@v3
    - name: Getting depends
      run: apt-get update && apt-get install gcc meson m4 g++ file -y
    - name: Print g++ architecture
      run: g++ -dumpmachine
    - name: Temp step create mconfig.h
      run: make mconfig && make -C build && build/tools/mconfig-gen > src/includes/mconfig.h
    - name: Prepare Build
      run: meson setup builddir
    - name: Build
      run: meson compile -C builddir
    - name: Print dinit executive file architecture
      run: file ./builddir/dinit
    # for now; meson dont support Unit & intergration tests
    #- name: Unit tests
    #  run: make check
    #- name: Integration tests
    #  run: make check-igr
